# Generated by Django 5.0.6 on 2024-05-17 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='type_de_don',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
