# Generated by Django 5.0.6 on 2024-05-23 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globalApp', '0002_annonce_type_de_don'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifenvoyer',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='notifenvoyer',
            name='utilisateur',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='NotifEnvoyer',
        ),
    ]
