# Generated by Django 5.0.6 on 2024-05-23 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalApp', '0003_remove_notifenvoyer_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
