# Generated by Django 5.0.6 on 2024-06-01 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalApp', '0004_annonce_latitude_annonce_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='date_de_signalement',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
